name: ci

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-changes.yml

  secret-scan:
    uses: ./.github/workflows/secret-scan.yml
    with:
      mode: incremental

  lint-test:
    needs: detect-changes
    if: needs.detect-changes.outputs.has_changes == 'true'
    uses: ./.github/workflows/lint-test.yml
    with:
      matrix: ${{ needs.detect-changes.outputs.matrix }}

  sast:
    uses: ./.github/workflows/sast.yml

  dependency-scan:
    needs: [detect-changes, lint-test]
    if: needs.detect-changes.outputs.has_changes == 'true'
    uses: ./.github/workflows/dependency-scan.yml
    with:
      matrix: ${{ needs.detect-changes.outputs.matrix }}

  helm-lint:
    needs: detect-changes
    if: needs.detect-changes.outputs.helm_changed == 'true'
    uses: ./.github/workflows/helm-lint.yml
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

  build-and-scan-images:
    permissions:
      contents: read
      packages: write
    needs: [detect-changes, lint-test, sast, dependency-scan, secret-scan]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.detect-changes.outputs.has_changes == 'true'
    uses: ./.github/workflows/build-scan-images.yml
    with:
      matrix: ${{ needs.detect-changes.outputs.matrix }}

  post-build:
    permissions:
      contents: read
      packages: write
      id-token: write
    needs: [detect-changes, build-and-scan-images]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.detect-changes.outputs.has_changes == 'true'
    uses: ./.github/workflows/post-build.yml
    with:
      sign_matrix: ${{ needs.detect-changes.outputs.matrix }}

  dast:
    needs: build-and-scan-images
    if: github.event_name == 'push'
    uses: ./.github/workflows/dast.yml
    secrets:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

  deploy:
    permissions:
      contents: read
    needs: [helm-lint, build-and-scan-images, post-build, dast]
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}